### ISSUE TITLE
How to tell if the service is down from metrics exposed?

### ISSUE THREAD

**Issue by motonisar** [abraham-leal/ccloud-schema-exporter#14]
We are currently running "ccloud-schema-exporter" as a Kubernetes pod with the metrics end point exposed. We want to setup alerts to check if the service is up and running. I tried killing the pod/deployment and could still find the metrics end point exposing some data.

Is there any metrics value used to tell if the ccloud-schema-exporter is running(Up or down)? We want to determine when ccloud-schema-exporter is down, so team could recover in case of any issues?

**Comment by abraham-leal** [comment]
Hi @motonisar, the /metric endpoint will keep emitting until the process is killed. Do keep in mind that ccloud-schema-exporter tries to gracefully shut down when given a SIGTERM (and this might take a bit as it finishes the current sync loop). I'd say to know the exporter is running, the availability of the /metrics endpoint is a good indicator. In kubernetes, I'd probably make my liveliness probe query /metrics and as long as 200 is returned things should be up.

Did you wait a bit for graceful shutdown when sending a SIGTERM to the pod?

**Comment by motonisar** [comment]
@abraham-leal Thank you for the quick response. I waited until the pod completed died and no longer existed. The metrics still continues to be up and return values which is not usual as the backend pod no longer runs. I did add the /metrics port 9020 to liveness probe. It continues to return "HTTP/1.1 200 OK" even though the pod no longer exist.

**Comment by abraham-leal** [comment]
@motonisar I am not able to replicate this scenario. When deploying in k8s with a LB, if the `ccloud-schema-exporter` is up the metrics will return, otherwise the call hangs. Could it be that you are deleting the pod and k8s is just recreating it right away so you don't notice the pod being gone? If not, please do let me know how to reproduce this behavior.

**Comment by abraham-leal** [comment]
Hi @motonisar, is your issue resolved? This seems stale. Please let me know, if not, I'll close the issue.

**Comment by motonisar** [comment]
Yes , Sorry i forgot to update you back. The issue was with multiple deployments running using the same app selector causing the endpoint to show always up. At any given point one of the deployment was up, Once the app selector was changed it and made unique it worked. Thanks for your patience and help !
