### ISSUE TITLE
Apeending full path to subject name in windows enviorement 

### ISSUE THREAD

**Issue by gssran** [abraham-leal/ccloud-schema-exporter#27]
When we are uplaoding the schema registry using -fromLocalCopy it upload full path as name of schema registry
e.g D:\\Schematest\\SchemaRegistryBackup\\myNew-Topic-value-1-35421-JSON is the name instead of  myNew-Topic-value-1-35421-JSON

**Comment by abraham-leal** [comment]
Closing as PR merged
